services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend

  api:
    build: ./api
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      CORS_ORIGINS: ${CORS_ORIGINS}
      PASSWORD_PEPPER: ${PASSWORD_PEPPER}
      SECRET_KEY: ${SECRET_KEY}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    networks:
      - backend

  web:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/webroot:/var/www/certbot
      - ./nginx/robots.txt:/etc/nginx/static/robots.txt
      - ./client/dist/client/browser:/usr/share/nginx/html
    depends_on:
      - api
    networks:
      - backend
      - frontend

  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/webroot:/var/www/certbot
    entrypoint: >
      sh -c "certbot certonly --webroot -w /var/www/certbot --non-interactive --agree-tos --email necsus.dev@proton.me -d altertracker.com -d www.altertracker.com"
    depends_on:
      - web
    networks:
      - frontend

volumes:
  db_data:

networks:
  frontend:
  backend: