apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: altertracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: registry.altertracker.com/altertracker-api:latest
          ports:
            - containerPort: 5001
          envFrom:
            - secretRef:
                name: api-secret
          # Si tu as besoin d'une readiness/liveness probe, ajoute-les ici