apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: altertracker-ingress
  namespace: altertracker
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - altertracker.com
        - www.altertracker.com
      secretName: altertracker-tls
  rules:
    - host: altertracker.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: angular
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 80
          - path: /socket.io/
            pathType: ImplementationSpecific
            backend:
              service:
                name: api
                port:
                  number: 80
          - path: /robots.txt
            pathType: ImplementationSpecific
            backend:
              service:
                name: static-files
                port:
                  number: 80
          - path: /ads.txt
            pathType: ImplementationSpecific
            backend:
              service:
                name: static-files
                port:
                  number: 80
          - path: /sitemap.xml
            pathType: ImplementationSpecific
            backend:
              service:
                name: static-files
                port:
                  number: 80