apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  namespace: altertracker
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      # Block bad IPs
      geo $bad_ip {
        default 0;
        52.47.134.158 1;
        13.37.84.159 1;
        51.44.100.120 1;
        87.255.194.135 1;
      }
      map $bad_ip $loggable {
        1 0;
        0 1;
      }
      if ($bad_ip) {
        return 403;
      }
    nginx.ingress.kubernetes.io/server-snippet: |
      access_log /var/log/nginx/access.log combined if=$loggable;
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - altertracker.com
      secretName: altertracker-tls
  rules:
    - host: altertracker.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 5001
          - path: /socket.io/
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 5001
          - path: /
            pathType: Prefix
            backend:
              service:
                name: angular
                port:
                  number: 80
    - host: www.altertracker.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: angular
                port:
                  number: 80